version: '3.7'

services:
  app:
    image: localhost:5000/zetter-frontend-app:${VERSION}
    build:
      context: .
      target: ${CONTAINER_TARGET}
      dockerfile: ./cd/node/Dockerfile
    container_name: zg-frontend-app
    ports:
      - ${PORT}:${PORT}
    user: ${RUNNING_USER}
    volumes:
      - frontend_modules:/app/node_modules
      - /var/log/zetter-frontend:/logs:rw

volumes:
  frontend_modules:
    name: zetter-frontend-modules
