version: '3.7'

services:
  app:
    build:
      context: .
      target: ${CONTAINER_TARGET}
      dockerfile: ./cd/node/Dockerfile
      args:
        RUNNING_USER: ${RUNNING_USER}
    container_name: zg-frontend-app
    ports:
      - ${PORT}:${PORT}
      - "9235:9229"
    environment:
      - PORT=${PORT}
      - NEXT_INTERNAL_API_URI=${NEXT_INTERNAL_API_URI}
      - NEXT_PUBLIC_API_URI=${NEXT_PUBLIC_API_URI}
      - NEXT_PUBLIC_STATIC_URI=${NEXT_PUBLIC_STATIC_URI}
      - NEXT_PUBLIC_FRONTEND_URI=${NEXT_PUBLIC_FRONTEND_URI}
    volumes:
      - ./logs:/logs:rw