version: '3.8'

services:
  app:
    image: ${MANAGER_IP:-127.0.0.1}:5000/zetter-frontend-app:${VERSION:-main}
    build:
      context: .
      target: ${CONTAINER_TARGET:-production-run-stage}
      dockerfile: ./cd/node/Dockerfile
      args:
        RUNNING_USER: ${RUNNING_USER}
        NODE_ENV: production
    container_name: zg-frontend-app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NEXT_PUBLIC_API_URI=${NEXT_PUBLIC_API_URI}
      - NEXT_PUBLIC_STATIC_URI=${NEXT_PUBLIC_STATIC_URI}
      - NEXT_PUBLIC_FRONTEND_URI=${NEXT_PUBLIC_FRONTEND_URI}
    user: ${RUNNING_USER}
    volumes:
      - /var/log/zetter-frontend:/logs:rw