# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hetzner Production node.js

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: [ self-hosted, production ]
    strategy:
      matrix:
        node-version: [ 24.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Update secrets
        run: 'echo "$PRODUCTION_ENV" > .env.production'
        env:
          PRODUCTION_ENV: ${{secrets.PRODUCTION_ENV}}
      - name: Get Manager IP
        id: manager_ip
        run: echo "IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: 'Build app container'
        run: |
          set -a 
          . .env.production 
          set +a
          docker compose --env-file=.env.production -f docker-compose.prod.yml -p zg-frontend build app
        env:
          VERSION: ${{ github.ref_name }}
          RUNNING_USER: ${{ secrets.HETZNER_RUNNING_USER }}
      - name: 'Push API container to local registry'
        run: |
          set -a 
          . .env.production 
          set +a
          docker compose --env-file=.env.production -f docker-compose.prod.yml -p zg-frontend push app
        env:
          VERSION: ${{ github.ref_name }}
          RUNNING_USER: ${{ secrets.HETZNER_RUNNING_USER }}
          MANAGER_IP: ${{ steps.manager_ip.outputs.IP }}

  deploy:
    runs-on: self-hosted
    needs:
      - build-and-push
    steps:
      - name: Update secrets
        run: 'echo "$PRODUCTION_ENV" > .env.production'
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
      - name: Get Manager IP
        id: manager_ip
        run: echo "IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Deploy to swarm
        run: |
          set -a 
          . .env.production 
          set +a
          docker stack deploy -c docker-compose.prod.yml --with-registry-auth zg-frontend
        env:
          VERSION: ${{ github.ref_name }}
          RUNNING_USER: ${{ secrets.HETZNER_RUNNING_USER }}
          MANAGER_IP: ${{ steps.manager_ip.outputs.IP }}
